class Formes:
    CARRE = "carre"
    RECTANGLE = "rectangle"

class Couleurs:
    ROUGE = "rouge"
    BLANC = "blanc"
    NOIR = "noir"
    VERT = "vert"
    BLEU = "bleu"
    JAUNE = "jaune"
    MARINE = "marine"
    CITRONVERT = "citron vert"
    SARCELLE = "sarcelle"
    GRIS = "gris"
    BORDEAUX = "bordeaux"
    CYAN = "cyan"
    OLIVE = "olive"
    VIOLET = "violet"
    MAGENTA = "magenta"
